language: node_js
cache:
  directories:
    - $HOME/.npm
notifications:
  email:
    on_failure: always
node_js:
  - "8.10"
install:
  - npm install
script:
  - npm run lint
deploy:
  skip_cleanup: true
  provider: script
  script: npm run deploy
  on:
    branch: master
