version: 2.1
executors:
  node-aws-lambda:
    docker:
      - image: circleci/node:8.10
  python3-node:
    docker:
      - image: circleci/python:3.6.8-node
commands:
  deploy:
    parameters:
      stage:
        type: string
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - add_ssh_keys:
          fingerprints:
            - '9e:3f:ef:64:be:36:57:51:9d:44:fb:a0:05:2f:89:fd'
      - run:
          name: Install awscli
          command: sudo pip install awscli
      - run:
          name: Sync S3 assets
          command: aws s3 sync assets/ s3://pyphoy/assets
      - run:
          name: Deploy to EC2
          command: npx pm2 deploy << parameters.stage >> update
jobs:
  build:
    executor: node-aws-lambda
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - run: npm run build
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
  deploy-prod:
    executor: python3-node
    steps:
      - deploy:
          stage: production

  deploy-dev:
    executor: python3-node
    steps:
      - deploy:
          stage: development

workflows:
  build_test_and_deploy:
    jobs:
      - build
      - deploy-dev:
          requires:
            - build
          filters:
            branches:
              only: develop
      - deploy-prod:
          requires:
            - build
          filters:
            branches:
              only: master
