version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.10
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: npm install
      - run: npm run build
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
  lint:
    docker:
      - image: circleci/node:8.10
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: npm run lint
  # test:
  #   docker:
  #     - image: circleci/node:8.10
  #   working_directory: ~/repo
  #   steps:
  #     - checkout
  #     - restore_cache:
  #         keys:
  #           - v1-dependencies-{{ checksum "package.json" }}
  #           # fallback to using the latest cache if no exact match is found
  #           - v1-dependencies-
  #     - run: npm run test
  sync:
    docker:
      - image: circleci/node:8.10
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Add ~/.local/bin to PATH
          command: |
            echo 'export PATH=/home/circleci/.local/bin:$PATH' >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Intall awscli
          command: |
            sudo apt-get -y -qq update
            sudo apt-get -y -qq install python3.4-dev
            curl -O https://bootstrap.pypa.io/get-pip.py
            python3.4 get-pip.py --user
            pip install awscli --upgrade --user
      - run:
          name: Sync S3 assets
          command: npm run sync:assets
  deploy:
    docker:
      - image: circleci/node:8.10
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - add_ssh_keys:
          fingerprints:
            - "10:27:4f:6b:3a:d7:0f:2f:bc:53:77:5b:88:bd:7a:e3"
      - run: npm run deploy:site

workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - build
      - lint:
          requires:
            - build
      # - test:
      #     requires:
      #       - build
      - sync:
          requires:
            - lint
            # - test
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - lint
            # - test
          filters:
            branches:
              only: master
