version: 2.1
executors:
  node-aws-lambda:
    docker:
      - image: circleci/node:10
  python3-node:
    docker:
      - image: circleci/python:3.6.8-node
commands:
  deploy:
    parameters:
      stage:
        type: string
    steps:
      - checkout
      - restore_cache:
          keys:
            - v3-dependencies-{{ checksum "package.json" }}
            - v3-dependencies-
      - add_ssh_keys:
          fingerprints:
            - '32:b0:75:8c:c6:2c:70:45:48:92:09:df:b3:0b:77:ad'
            - '56:0c:6e:91:71:03:b7:95:28:14:c2:b0:37:e8:a0:07'
      - run:
          name: Install awscli
          command: sudo pip install awscli
      - run:
          name: Sync S3 assets
          command: aws s3 sync assets/ s3://pyphoy/assets
      - run:
          name: Deploy to EC2
          command: npx pm2 deploy << parameters.stage >> update
jobs:
  build:
    executor: node-aws-lambda
    steps:
      - checkout
      - restore_cache:
          keys:
            - v3-dependencies-{{ checksum "package.json" }}
            - v3-dependencies-
      - run: npm install
      - run: npm run build
      - save_cache:
          key: v3-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
  deploy-prod:
    executor: python3-node
    steps:
      - deploy:
          stage: production

  deploy-dev:
    executor: python3-node
    steps:
      - deploy:
          stage: development

workflows:
  build_test_and_deploy:
    jobs:
      - build
      - deploy-dev:
          requires:
            - build
          filters:
            branches:
              only: develop
      - deploy-prod:
          requires:
            - build
          filters:
            branches:
              only: master
