version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:8.10
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: npm install
      - run: npm run build
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
  deploy:
    docker:
      - image: circleci/node:8.10
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - add_ssh_keys:
          fingerprints:
            - "9e:3f:ef:64:be:36:57:51:9d:44:fb:a0:05:2f:89:fd"
      - run:
          name: Intall awscli
          command: |
            sudo apt-get install python3 python3-pip -y
            sudo pip3 install awscli --upgrade
      - run:
          name: Sync S3 assets
          command: npm run sync:assets
      - run:
          name: Deploy to EC2
          command: npm run deploy:site

workflows:
  build_test_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
